### ISSUE TITLE
max_line_length setting ignored?

### ISSUE THREAD

**Issue by codejet** [AtomLinter/linter-coffeelint#10] opened 2014-07-11 12:22 UTC
I get warnings about lines exceeding the maximum length. Those lines are longer than 80 characters though, and the default `max_line_length` should be 120 (in coffeelint.json). I did not overwrite it. I event tried adding it to ~/.atom/config.cson, but still no luck. Do I miss something here?

**Comment by AsaAyers** [comment] 2015-03-19 19:21
This should be fixed in v0.2.0. Please reopen if you're still having issues.

**Closed by AsaAyers** 2015-03-19 19:21 UTC

**Comment by ericop** [comment] 2015-03-31 20:19
This is still an issue for me today on Mac OS @AsaAyers

**Comment by AsaAyers** [comment] 2015-03-31 20:23
When you run `coffeelint` from the commandline does it pick up your configuration? [configuration docs](https://github.com/clutchski/coffeelint/blob/master/doc/user.md)

**Comment by ericop** [comment] 2015-03-31 21:17
Are you saying I can run `coffeelint` from the folder where Atom set and that i can have an Atom json file to configure this, or that it still only works via a projects specific rules? We have a Brunch config.coffee file with the following in it, so no package.json.

    coffeelint:
      options:
        no_stand_alone_at: level: "error"
        space_operators: level: "error"
        no_interpolation_in_single_quotes: level: "error"
        no_unnecessary_fat_arrows: level: 'error'
        max_line_length: value: 110
        cyclomatic_complexity:
          value: 10
          level: "error"
        no_set_timeout:
          module: "./lint/noSetTimeout"
        no_set_interval:
          module: "./lint/noSetInterval"

**Comment by ericop** [comment] 2015-04-03 16:32
Just for those who come later, this :boom:  **max_line_length** :exclamation: still occurs be default on any line over 80 characters. In my Mac OS #HOME folder I stuck in `coffeelint.json` with the following, and got what I was after:

        {
          "max_line_length": {
            "name": "max_line_length",
            "value": 110,
            "level": "warn",
            "limitComments": true
          }
        }

**Comment by bobrocke** [comment] 2015-05-17 15:47
Any chance of a fix, or has this package been abandoned?

**Comment by AsaAyers** [comment] 2015-05-17 16:19
This package has not been abandoned. I don't see a problem here I can reproduce to fix.

CoffeeLint will resolve a configuration by looking in the same folder for `coffeelint.json`, then repeat. If it gets to the root of your drive and still hasn't found a config to use it will use `$HOME/coffeelint.json`. If you can open a terminal and run `coffeelint path/to/your/file.coffee` and it picks up the config but `linter-coffeelint` doesn't, then there's a bug that I will fix ASAP.

**Comment by AsaAyers** [comment] 2015-05-17 16:21
same folder = same folder as the file you are linting. If your project lives in

`/projects/my-project` and your linting `src/something.coffee` it will check:

`/projects/my-project/src/coffeelint.json`
`/projects/my-project/coffeelint.json`
`/projects/coffeelint.json`
`/coffeelint.json`
`$HOME/coffeelint.json` (or whatever is appropriate for your OS)

**Comment by bobrocke** [comment] 2015-05-17 16:24
So, is `/coffeelint.json` explicitly not `.atom/packages/linter-coffeelint/coffeelint.json`?

**Comment by AsaAyers** [comment] 2015-05-17 16:31
yes, the `coffeelint.json` that is committed in `linter-coffeelint` is simply the rules for this project. If it doesn't find any configuration file it just lets CoffeeLint use the default values, which includes setting `max_line_length` to 80 and `error`

The `linter-coffeelint/coffeelint.json` (and this issue) predate my joining this project. I didn't realize people would think that is the default. I'll clean up (or maybe remove) the file from this repo

**Comment by bobrocke** [comment] 2015-05-17 17:28
Maybe allow that file to be edited and be the last one checked? That way any other `coffeelint.json` files will override it, but the default can still be changed.

**Comment by AsaAyers** [comment] 2015-05-17 17:41
If you want a global default create a `$HOME/coffeelint.json`. The whole
point of this strategy is that you configure your project not your editor.
That way the next person to work in your code base using a different editor
doesn't have to waste time trying to figure out how to make his editors
config match yours.

**Comment by bobrocke** [comment] 2015-05-17 17:45
I understand. But there are many Atom packages that have local settings - many, including myself, would look to that, first.

On Mac OS X, by `$HOME`, do you mean `/Users/bob`, for me?

**Comment by AsaAyers** [comment] 2015-05-17 18:04
`envs = process.env.USERPROFILE or process.env.HOME or process.env.HOMEPATH`
[yes](https://github.com/clutchski/coffeelint/blob/master/src/configfinder.coffee#L52)

From what I can tell going and editing the plugin code directly is always the wrong strategy. If the package were configurable it would have a settings button. 

![selection_002](https://cloud.githubusercontent.com/assets/324999/7671415/6a075aa4-fc9d-11e4-829e-7abff077f0d1.png)

Instead the README.md addresses settings:

> ## Settings
>
> As of v0.2.0 there is no need to specify a path to coffeelint. If you need to use a specific version you can specify it in your project's `package.json` and `linter-coffeelint` will use that one. This is the same behavior the coffeelint commandline gives you.
> 
> Your configuration belongs in your project, not your editor.
https://github.com/clutchski/coffeelint/blob/master/doc/user.md

In an attempt to remove any future confusion I have removed the `coffeelint.json` from this project as the defaults are fine.

**Comment by ericop** [comment] 2015-05-17 18:46
Still, I think the bottom line is that the line length error is defaults to
too short a value, correct?

**Comment by AsaAyers** [comment] 2015-05-18 00:37
Your opinion is that the default is too short. That's why it's a default and you can configure it.

It's not too short for [PEP-8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)

> Limiting the required editor window width makes it possible to have several files open side-by-side, and works well when using code review tools that present the two versions in adjacent columns.

or Atom's default column guide:

![selection_003](https://cloud.githubusercontent.com/assets/324999/7672889/9774412a-fcd2-11e4-9831-bf1d11d6efd3.png)

Or my screen when I need a terminal (usually running tests on every save) and an editor (with the tree view removed)

![workspace 3_004](https://cloud.githubusercontent.com/assets/324999/7672941/6f3a5f9e-fcd4-11e4-972d-474ac57e53fa.png)

**Comment by chitsaou** [comment] 2015-06-10 07:37
I added a `coffeelint.json` in my project's root dir and it works

```json
{
  "max_line_length": {
    "value": 9999
  },
  "coffeelint": {
    "transforms": [ "coffee-react-transform" ]
  }
}
```

**Comment by AsaAyers** [comment] 2015-06-10 13:28
use `ignore` to turn off a rule.

```json
{
  "max_line_length": {
    "level": "ignore"
  },
  "coffeelint": {
    "transforms": [ "coffee-react-transform" ]
  }
}
```

**Comment by chitsaou** [comment] 2015-06-10 13:29
@AsaAyers thank you, didn't noticed this option :p

**Comment by archcorsair** [comment] 2015-07-14 07:27
@AsaAyers coffeelint crashes as soon as I open Atom with coffeelint.json in my project root. I tried both `"level": "ignore"` and `"value": 9999`

**Comment by AsaAyers** [comment] 2015-07-14 10:31
please define "crashes"

**Comment by archcorsair** [comment] 2015-07-14 16:39
@AsaAyers coffeelint shows a generic error `CoffeeLint crashed, see console for error details..`

Here's what I have in my console:
```
C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\core.coffee:79 Cannot find module 'coffee-react-transform' from 'D:\Desktop\etsy2015\app\assets'
C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\core.coffee:80 Error: Cannot find module 'coffee-react-transform' from 'D:\Desktop\etsy2015\app\assets'
  at module.exports (C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\node_modules\resolve\lib\sync.js:32:11)
  at C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\lib\configfinder.js:89:16
  at Array.map (native)
  at expandModuleNames (C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\lib\configfinder.js:88:53)
  at Object.exports.getConfig (C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\lib\configfinder.js:115:16)
  at Object.module.exports.lint (C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\core.coffee:68:29)
  at _Class.module.exports._Class.lint (C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\plus-linter.coffee:44:19)
  at _Class.lint (C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\plus-linter.coffee:1:1)
  at C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:69:26
  at currentLinter (C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:68:20)
  at C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:64:26)
  at C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:57:27

C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\core.coffee:79 Cannot find module 'coffee-react-transform' from 'D:\Desktop\etsy2015\app\assets'
C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\core.coffee:80 Error: Cannot find module 'coffee-react-transform' from 'D:\Desktop\etsy2015\app\assets'
  at module.exports (C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\node_modules\resolve\lib\sync.js:32:11)
  at C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\lib\configfinder.js:89:16
  at Array.map (native)
  at expandModuleNames (C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\lib\configfinder.js:88:53)
  at Object.exports.getConfig (C:\Users\archc_000\.atom\packages\linter-coffeelint\node_modules\coffeelint\lib\configfinder.js:115:16)
  at Object.module.exports.lint (C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\core.coffee:68:29)
  at _Class.module.exports._Class.lint (C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\plus-linter.coffee:44:19)
  at _Class.lint (C:\Users\archc_000\.atom\packages\linter-coffeelint\lib\plus-linter.coffee:1:1)
  at C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:69:26
  at currentLinter (C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:68:20)
  at C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:64:26)
  at C:\Users\archc_000\.atom\packages\linter\lib\editor-linter.coffee:57:27
```

**Comment by AsaAyers** [comment] 2015-07-14 17:29
> Cannot find module 'coffee-react-transform' from

It looks like you configured CoffeeLint to use `coffee-react-transform` but it isn't in your `node_modules`

**Comment by archcorsair** [comment] 2015-07-14 19:39
Wow, sorry. I blindly copy-pasted a commenter's code without looking at it. Face-palming for not seeing that. Works great now without `coffee-react-transform`
Thanks!

**Comment by rioc0719** [comment] 2015-07-29 00:17
> If you can open a terminal and run coffeelint path/to/your/file.coffee and it picks up the config but linter-coffeelint doesn't, then there's a bug that I will fix ASAP.

This is happening to me. The file I am editing and `coffeelint.json` are in the same directory (the project root), but none of the options are applied (i.e. I still get errors related to max line length even though I have `"max_line_length": {"level": "ignore" }` in `coffeelint.json`). There is nothing relevant in the console.

**Comment by AsaAyers** [comment] 2015-07-29 18:02
@rioc0719 I just published a patch. There was a bug that caused `linter-coffeelint` to look for your config relative to the directory the file was in, instead of relative to the file. Since I keep `coffeelint.json` in the root of my projects and my source lives in `src` or `lib` I didn't notice.

**Comment by rioc0719** [comment] 2015-07-29 20:12
@AsaAyers Thanks! The patch fixed the problem perfectly.
