### ISSUE TITLE
linter attempts to lint cjsx

### ISSUE THREAD

**Issue by FlorianWendelborn** [AtomLinter/linter-coffeelint#63] opened 2016-02-07 18:25 UTC
Shows error messages, when linting valid `.cjsx`.

[code this issue happened with](https://github.com/jsdf/coffee-reactify)

**Comment by AsaAyers** [comment] 2016-02-07 18:32
cjsx is not CoffeeScript and is not parsable by CoffeeScript. Because of this isn't isn't really supported by CoffeeLint.

What I can provide is a hack that has been reported to work. https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs If you setup CoffeeLint to use that transformer it will convert your cjsx (in-memory) to CoffeeScript and then will lint that. You will have no control over what it generates, so the most common problem you're going to find is that it's going to complain about lines being too long and there's no way to fix that. You just have to add directives to tell CoffeeLint to ignore that section of code.

**Comment by dodekeract** [comment] 2016-02-07 18:40
I am aware that coffeescript is not cjsx. The issue is that this linter attempts to parse it nevertheless. It should just ignore any .cjsx files.

**Comment by AsaAyers** [comment] 2016-02-07 18:48
ok, I'll reopen this but I don't really have a solution. Because CoffeeLint can be configured for cjsx, it is in the list of scopes linter-coffeelint will parse. I can turn it off which fixes it for you, but then anyone who has configured CoffeeLint to handle their cjsx files will lose the ability for them to lint it.

You might just need to use the `Linter: Toggle` command when working with cjsx.

**Comment by dodekeract** [comment] 2016-02-07 18:51
Is it possible to implement a checkbox in the package settings, which turns it off for .cjsx files?

**Comment by AsaAyers** [comment] 2016-02-07 19:02
That sounds like the implementation of that would become a hacky solution, so I'd like to avoid it. This project does almost nothing. It just dispatches a call out to CoffeeLint and then formats the response for Linter to read it.

`linter-coffeelint` tells `linter` which scopes it supports. Linter checks the scopes of whatever files you're using and then distributes them to the appropriate linters. `linter-coffeelint` would still get called, but then have to check the preferences constantly and exit early claiming everything passed when really it didn't do any checks.

I highly recommend if you can, just moving to ES6 /w Babel. CoffeeScript doesn't have a future and cjsx support is terrible (as you can see here).

@Arcanemagus do you have any suggestions? Is there a solution that might make sense to have the core linter handle instead?

**Comment by dodekeract** [comment] 2016-02-07 19:08
I know this is a somewhat off-topic question, but why do you think CoffeeScript doesn't have a future? I just moved from ES6/Babel to CS, because I really like the syntax of CS.

**Comment by AsaAyers** [comment] 2016-02-07 19:28
(This is an updated version of comments I have made elsewhere)

CoffeeScript is dead or dying.

* CoffeeScript added Generators, but It's just too bad you don't get [a loop syntax that can use them](https://github.com/jashkenas/coffeescript/issues/3832)
* [CoffeeScript Redux](https://github.com/michaelficarra/CoffeeScriptRedux/commits/master) has had 3 commits since May 2015. It's dead
* [I maintained CoffeeeLint](https://github.com/clutchski/coffeelint/graphs/contributors?from=2013-01-08&to=2015-10-30&type=c) for about 2 years and the internals of CoffeeScript are so bad you [can't reliably track variables](https://github.com/AsaAyers/coffeescope)

Because of that last point I expect CoffeeLint will never be able to warn about unused or undefined variables.

ES6 is a real standard that is being adopted. CoffeeScript is a pile of hacks that was useful for a while, but it's time is done. In [CODE GENIUS - Rise of the Transpilers by Jeremy Ashkenas
](https://www.youtube.com/watch?v=DspYurD75Ns) you can watch Jeremy Ashkenas proudly talk about the kinds of hacks he used to put it together.
 
His slide on Cheating starts at 11:56
> We like to cheat and make things easier for ourselves ... this is not koshure, it is introducing context sensitivity into the lexer process. If you took the actual class you would get an F doing this kind of thing. But it's just programming, it's just code. You can cheat if you want to cheat

pop quiz! Given this line of CoffeeScript`foo bar and hello world` which of these is the JavaScript it produces

1. `foo(bar) && hello(world)`
2. `foo(bar && hello(world))`

I got that example from [Goodbye CoffeeScript, Hello TypeScript](http://blog.heapanalytics.com/goodbye-coffeescript-hello-typescript/)

**Comment by Arcanemagus** [comment] 2016-02-07 19:45
In other linters that have support for a scope only when configured properly there is an option to enable that support (default disabled), so a PR that only adds the `csjx` scope when an option is enabled could solve this relatively simply. If you then need this to change on a per project setting you can look up the project-manager package.

This isn't really anything that the core linter should handle as the issue is that this linter is advertising support for a scope that it only works with after some apparently quite hacky transformations.

(For the record, I'm with @AsaAyers here in that you should just move to ES6/Babel, we are moving the linters all over to that slowly as people get around to it.)

**Comment by AsaAyers** [comment] 2016-02-07 19:48
Can you provide an example of how other linters are handling that? Since scope is just a property on an object we pass to linter, I don't know the right way to update linter with the new value.

**Comment by Arcanemagus** [comment] 2016-02-07 19:59
`linter-eslint` for example uses that model [here](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/src/main.js#L70) to enable support for HTML files (which requires a plugin to be enabled in the project's settings).

**Comment by Inve1951** [comment] 2018-03-23 15:46
@AsaAyers, @Arcanemagus, are there any plans to support JSX in coffeelint? CS2 added JSX support. This is perfectly valid coffee code now:
![image](https://user-images.githubusercontent.com/18194808/37838800-21cdebb2-2eb9-11e8-9d30-3d46d92db595.png)
CC: @GeoffreyBooth

**Comment by UziTech** [comment] 2020-01-16 19:53
this should be fixed in the latest update

**Closed by UziTech** 2020-01-16 19:53 UTC
Labels: enhancement
