### ISSUE TITLE
Failed to activate the linter-coffeelint package

### ISSUE THREAD

**Issue by zerozodix** [AtomLinter/linter-coffeelint#58] opened 2015-10-25 06:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint) package, v1.1.2

### Stack Trace

Failed to activate the linter-coffeelint package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.module.exports.activate (/Users/zerozodix/.atom/packages/linter-coffeelint/lib/init.coffee:13:5)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "coffee-refactor",
      "refactor"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
go-plus, v3.5.1
linter, v1.8.1
linter-coffeelint, v1.1.2
vim-mode, vundefined

# Dev
No dev packages
```

**Comment by AsaAyers** [comment] 2015-10-25 13:43
Without any steps to reproduce this, my best guess would be to uninstall `linter-coffeelint` and re-install it. It definitely should have installed `atom-package-deps` based on the [package.json](https://github.com/AtomLinter/linter-coffeelint/blob/master/package.json#L23)

**Comment by Arcanemagus** [comment] 2015-12-09 02:45
Marking this as closed, looks like this was a partial install and the steps outlined above should fix it for you.

**Closed by Arcanemagus** 2015-12-09 02:45 UTC
